[5.0] KSTE-5: look up blacklist in bulk
2600hz/kazoo-ecallmgr pull request #112
Opened 2021-11-12 16:08 UTC by oguerrero913

2021-11-18 19:47 UTC, icehess requested changes

2021-11-18 19:47 UTC, icehess commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +    lists:foldl(fun block_call_routine/3, [Map, Blacklist], Routines).
```suggestion
    lists:foldl(fun(Routine, MapAcc) -> block_call_routine(Routine, MapAcc, Block) end, Map, Routines).
```

2021-11-18 19:47 UTC, icehess commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +            E;
Let's not change this line, return empty list.

2021-11-18 19:47 UTC, icehess commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +    case kz_datamgr:get_results(AccountDb, <<"blacklists/listing_by_number">>, ViewOptions) of
This view doesn't exists. Use `crossbar_listings/by_type_number`. The `key` is `[kzd_blacklists:type(), Normalized]`.

2021-11-18 19:47 UTC, icehess commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
>      is_number_blacklisted(get_blacklist(JObj), JObj).
You don't need to fetch blacklist again.

2021-11-18 19:48 UTC, icehess commented
4.3 PR: https://github.com/2600hz/kazoo/pull/6724

2022-01-12 21:49 UTC, icehess commented
* Required PRs
   * https://github.com/2600hz/kazoo-core/pull/366
* master pr: https://github.com/2600hz/kazoo-ecallmgr/pull/134

2023-11-14 18:07 UTC, manushiperera commented
Hello @icehess,
Is this still relevant?

2023-11-15 17:40 UTC, icehess commented
Not sure, see the comment on master PR. Also 5.0 is not supported anymore. So maybe it is safe to close this one? idk.

2026-04-12 17:58 UTC, closed without merging