Fetch with registrar
2600hz/kazoo-ecallmgr pull request #13
Opened 2020-07-31 16:00 UTC by lazedo

2020-07-31 23:59 UTC, icehess requested changes

2020-07-31 23:59 UTC, icehess commented on src/ecallmgr_registrar.erl
> +-spec lookup_endpoint(kz_term:ne_binary(), kz_term:ne_binary()) ->
`s/kz_term:ne_binary/binary/`

2020-07-31 23:59 UTC, icehess commented on src/ecallmgr_registrar.erl
> +                      ,endpoint_info :: kz_json:api_object() | '_'
It seems the value is `kz_json:object()`. Also there is no type `kz_json:api_object` (it is `kz_term:api_object`)

2020-08-01 00:17 UTC, lazedo commented on src/ecallmgr_registrar.erl
> +                      ,endpoint_info :: kz_json:api_object() | '_'
`kz_term:api_object` as it is created as undefined

2020-08-01 00:21 UTC, lazedo commented on src/ecallmgr_registrar.erl
> +-spec lookup_endpoint(kz_term:ne_binary(), kz_term:ne_binary()) ->
lol, spec was copied from 
```
-spec lookup_proxy_path(kz_term:ne_binary(), kz_term:ne_binary()) ->
          {'ok', kz_term:api_ne_binary(), kz_term:proplist()} |
          {'error', 'not_found'}.
```
which i think was copied from
```
-spec lookup_contact(kz_term:ne_binary(), kz_term:ne_binary()) ->
          {'ok', kz_term:ne_binary(), kz_term:proplist()} |
          {'error', 'not_found'}.
```

and they both handle the `<<>>`

2020-08-01 00:25 UTC, merged