KZOO-271: Add stateless endpoint_limit functionality
2600hz/kazoo-ecallmgr pull request #199
Opened 2022-11-09 18:47 UTC by harenson

Related to:
- https://github.com/2600hz/kazoo-crossbar/pull/362
- https://github.com/2600hz/kazoo-core/pull/512

Allows caller to know whether or not, the given endpoint has reached its configured limit by comparing given endpoint's limit with the current number of ongoing calls for the given endpoint.

2022-11-22 22:17 UTC, danielfinke requested changes

2022-11-22 22:17 UTC, danielfinke commented on src/ecallmgr_fs_endpoint_limit.erl
> +-define(SERVER, ?MODULE).
unused macro
```suggestion
```

2022-11-22 22:17 UTC, danielfinke commented on src/ecallmgr_fs_endpoint_limit.erl
> +    publish_enforce_endpoint_limit_resp(JObj, CurrentCount =:= EndpointLimit).
It seems like there is a chance 2 calls could come in at the same time in different zones leading to `CurrentCount >= EndpointLimit`. Maybe check for that just in case?
```suggestion
    publish_enforce_endpoint_limit_resp(JObj, CurrentCount >= EndpointLimit).
```

2022-11-22 22:48 UTC, lazedo requested changes
marking this as not mergeable

2022-11-22 23:33 UTC, lazedo commented
mostly comment on the core pr.
lets merge first only the changes required to implement the 2 new channel queries

2022-11-23 19:24 UTC, harenson commented on src/ecallmgr_fs_endpoint_limit.erl
> +-define(SERVER, ?MODULE).
Removed.

2022-11-23 19:28 UTC, harenson commented on src/ecallmgr_fs_endpoint_limit.erl
> +    publish_enforce_endpoint_limit_resp(JObj, CurrentCount =:= EndpointLimit).
This counts existing channels, if the given _endpoint_ has _endpoint_limit_ in use channels across the zones, it should include `Has-Reached-Limit: true` in the response. This functionality is supposed to be called before creating a channel.

2022-11-23 19:30 UTC, lazedo commented
@harenson move this to draft

2022-11-23 19:40 UTC, harenson commented
@lazedo Done, what changes do you want me to do before marking it as ready for review again?

2023-01-16 15:45 UTC, closed without merging