KZOO-308: Functionality to Intercept Users According to CALEA Intercept Requests
2600hz/kazoo-ecallmgr pull request #223
Opened 2023-03-13 19:43 UTC by nkarunarathne

This new listener (ecallmgr_wiretap_listener) listens to wiretap start recording events and starts recording by call id without a control queue.

2023-03-29 19:31 UTC, icehess commented on src/call_control/ecallmgr_wiretap_listener.erl
> +    'true' = kapi_dialplan:record_call_v(JObj),
Since you are listening to all dialplan call commands, you could get non recording command and this validation would crash, no?

2023-03-29 20:31 UTC, icehess requested changes

2023-03-29 20:31 UTC, icehess commented on src/call_control/ecallmgr_wiretap_listener.erl
> +    maybe_execute_command(JObj, kapi_dialplan:record_call_v(JObj)).
Hmm, the proper fix is to see what application is the command for, something like:

```erlang
handle_record_call(JObj, _Props) ->
    kz_log:put_callid(JObj),
    case kapi_dialplan:application_name(JObj) of
        <<"record_call">> ->
            'true' = kapi_dialplan:record_call_v(JObj),
            execute_command(JObj);
        _ ->
            'ok'
    end.
```

2023-04-02 05:03 UTC, lazedo commented
closing in favor of #230

2023-04-02 05:03 UTC, closed without merging