[master] KECA-40: loop_count not working when set in cf_play
2600hz/kazoo-ecallmgr pull request #244
Opened 2024-04-05 03:24 UTC by dhuynh-Kazoo

Currently, FreeSWTICH cannot understand the loop_playback command because wrong arg syntax

```
2024-04-05 02:28:32.245864 77.63% [ NOTICE] mq_cmd.c:00808 profile[command_handler] [5170] received command payload : {"Execute-Now":false,"Commands":[{"call-command":"execute","execute-app-name":"kz_multiset_encoded","execute-app-arg":"^^~playback_terminators=#*0123456789","event-uuid-name":"play"},{"call-command":"execute","execute-app-name":"loop_playback +3","execute-app-arg":"http_cache://http://admin:admin@127.0.0.1:5984/account%2F3a%2F5d%2F87bbc840dd361d9a180869bab3b6/038779773b7d0c556c6790f06f7322a6/uploaded_file_63851412342.mp3?rev=2-bc494a87c2f879187cb05f16f1ce443e","event-uuid-name":"play"}],"Call-ID":"EDfy0Ss44ahkc6g9WLSQjQ..","Core-UUID":"8bcef598-d915-40a1-8962-9bc5ee09bc12","Request-From-PID":"<0.15175.3>","Node":"kazoo_apps@2600hz.com","Msg-ID":"4e3fe2b1-2ff5-f1ee-971b-3e48a4c5c6ed","Event-Name":"commands","Event-Category":"freeswitch","App-Version":"5.0.0","App-Name":"ecallmgr_extension","AMQP-Worker-Consumer-Tag":"","AMQP-Worker-Delivery-Tag":28,"AMQP-Worker-Connection":"127.0.0.1-local","AMQP-Worker-Zone":"local","AMQP-Worker-Profile":"commands","AMQP-Worker-ID":0,"Server-ID":"consumer://commands/0/com-kazoo-api-9115d88d-95ee-1f8a-da2a-e5939c78
2024-04-05 02:28:32.269354 77.63% [  DEBUG] switch_ivr.c:00633 sofia/sipinterface_1/my_dell@2600hz.com Command Execute [depth=1] loop_playback +3(http_cache://http://admin:admin@127.0.0.1:5984/account%2F3a%2F5d%2F87bbc840dd361d9a180869bab3b6/038779773b7d0c556c6790f06f7322a6/uploaded_file_63851412342.mp3?rev=2-bc494a87c2f879187cb05f16f1ce443e)
2024-04-05 02:28:32.269354 77.63% [    ERR] switch_core_session.c:03155 Invalid Application loop_playback +3
```
After applying new format, loop_playback work as expected

```
2024-04-05 03:27:45.169607 74.17% [ NOTICE] mq_cmd.c:00808 profile[command_handler] [5171] received command payload : {"Execute-Now":false,"Commands":[{"call-command":"execute","execute-app-name":"kz_multiset_encoded","execute-app-arg":"^^~playback_terminators=#*0123456789","event-uuid-name":"play"},{"call-command":"execute","execute-app-name":"loop_playback","execute-app-arg":"+3 http_cache://http://admin:admin@127.0.0.1:5984/account%2F3a%2F5d%2F87bbc840dd361d9a180869bab3b6/038779773b7d0c556c6790f06f7322a6/uploaded_file_63851412342.mp3?rev=2-bc494a87c2f879187cb05f16f1ce443e","event-uuid-name":"play"}],"Call-ID":"8vS6PXzMDvBE23vcNrbuLQ..","Core-UUID":"8bcef598-d915-40a1-8962-9bc5ee09bc12","Request-From-PID":"<0.20887.7>","Node":"kazoo_apps@2600hz.com","Msg-ID":"71dd3079-ac22-6f4e-8770-46e2bfc00fe9","Event-Name":"commands","Event-Category":"freeswitch","App-Version":"5.0.0","App-Name":"ecallmgr_extension","AMQP-Worker-Consumer-Tag":"","AMQP-Worker-Delivery-Tag":39,"AMQP-Worker-Connection":"127.0.0.1-local","AMQP-Worker-Zone":"local","AMQP-Worker-Profile":"commands","AMQP-Worker-ID":0,"Server-ID":"consumer://commands/0/com-kazoo-api-74d7aeb0-abd3-e932-697b-485e250f2b3a","AMQP-Broadcast-Channel":"amqp.freeswitch.freeswitch.commands","AMQP-Broadcast-Key":"freeswitch.commands.8bcef598-d915-40a1-8962-9bc5ee09bc12"}
2024-04-05 03:27:45.186108 74.17% [  DEBUG] switch_ivr.c:00633 sofia/sipinterface_1/iphone_device@2600hz.com Command Execute [depth=1] loop_playback(+3 http_cache://http://admin:admin@127.0.0.1:5984/account%2F3a%2F5d%2F87bbc840dd361d9a180869bab3b6/038779773b7d0c556c6790f06f7322a6/uploaded_file_63851412342.mp3?rev=2-bc494a87c2f879187cb05f16f1ce443e)
2024-04-05 03:27:45.205823 74.17% [   INFO] switch_core_session.c:02962 EXECUTE [depth=1] sofia/sipinterface_1/iphone_device@2600hz.com loop_playback(+3 http_cache://http://admin:admin@127.0.0.1:5984/account%2F3a%2F5d%2F87bbc840dd361d9a180869bab3b6/038779773b7d0c556c6790f06f7322a6/uploaded_file_63851412342.mp3?rev=2-bc494a87c2f879187cb05f16f1ce443e)
```

2024-04-05 07:12 UTC, lazedo requested changes
- drop the unrelated changes to ecallmgr_fs_authz
- squash your commits

2024-04-05 13:33 UTC, dhuynh-Kazoo commented
hi @lazedo , I removed ecallmgr_fs_authz and squashed the commits

2024-04-05 14:43 UTC, lazedo approved these changes

2024-04-05 14:44 UTC, merged

2024-05-21 16:53 UTC, icehess commented
PRs:
- https://github.com/2600hz/kazoo-ecallmgr/pull/245 
- https://github.com/2600hz/kazoo-ecallmgr/pull/244