KPIV-17: move member flags under join options
2600hz/kazoo-ecallmgr pull request #246
Opened 2024-05-28 20:00 UTC by icehess

This moves member flags under `Join-Options` to make it easier for apps to send join flags for member in conference command without needing to update the code each time we want to add/support new flags.

2024-05-29 07:04 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +    case kz_json:to_proplist(JoinOptions) of
```suggestion
    case kz_json:to_proplist(<<"Join-Options">>, JObj) of
```

2024-05-29 07:06 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +                          ,{<<"endconf">>, <<"Endconf">>}
```suggestion
                          ,{<<"endconf">>, <<"End-Conference">>}
```

2024-06-03 09:06 UTC, lazedo approved these changes
lets wait for related pr to merge

2024-06-18 08:50 UTC, lazedo commented on test/ecallmgr_call_command_tests.erl
> +                             ,{<<"End-Conference">>, 'true'}
test will always fail ?

2024-06-18 08:51 UTC, lazedo requested changes
test seems to always fail

2024-07-02 18:50 UTC, icehess commented
@lazedo CI is passing now, anything else is needed for these PRs to be merged?

2024-07-25 17:47 UTC, merged