KPIV-20: adding silence detection variables to record_call
2600hz/kazoo-ecallmgr pull request #247
Opened 2024-05-30 20:15 UTC by icehess

Adds support for stop recording on silence detection for freeswitch `record_session` app.

Silence detection should be set explicitly to get enabled.

2024-05-30 20:15 UTC, icehess commented
PRs:
- master:
    - https://github.com/2600hz/kazoo-core/pull/848
    - https://github.com/2600hz/kazoo-ecallmgr/pull/247

2024-05-31 16:57 UTC, lazedo commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
I believe this is no longer needed because there's no translation with these variables

2024-05-31 16:57 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +                       ,{<<"RECORD_MIN_SEC">>, RecordMinSec}
no need for this change

2024-05-31 16:57 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> -                       ,{<<"record_min_sec">>, RecordMinSec}
and this

2024-05-31 16:58 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +    InitialTimeout = kz_json:get_integer_value(<<"Recrod-Silence-Initial-Timeout">>, JObj, 0),
`Recrod`

2024-05-31 16:58 UTC, lazedo requested changes
small things

2024-05-31 17:23 UTC, icehess commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
I think it is still needed, without this we get `ecallmgr_RECORD_THRESHOLD` and fs won't do silence detection.

2024-05-31 17:40 UTC, lazedo commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
you're right, I missed the `ecallmgr_util:process_fs_kv` call, my bad.

2024-05-31 17:44 UTC, lazedo commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
I'm not against "uppercasing"  `record_min_sec` (freeswitch handles it both cases) , but in that case remove the `{<<"record_min_sec">>, <<"record_min_sec">>}` from ecallmgr.hrl

2024-05-31 19:40 UTC, icehess commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
Regarding `record_min_sec` I think FS or at least `record_session` expect uppercase, see:
https://github.com/2600hz/freeswitch-stack/blob/v20.23.6/src/switch_ivr_async.c#L3385

Anyway, if set, doesn't have to discard if recorded less than minimum? I don't see it discarding in my testing.

2024-05-31 21:10 UTC, icehess commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
in any case I reverted the uppercase.

2024-05-31 22:00 UTC, lazedo commented on src/ecallmgr.hrl
> +                              ,{<<"RECORD_MIN_SEC">>, <<"RECORD_MIN_SEC">>}
follow the `get_recording_var` ands you'll noticed that it accepts either case

2024-06-03 08:56 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +    FinalTimeout = kz_json:get_integer_value([<<"Record-Silence-Detection">>, <<"Final-Timeout">>], JObj, 5),
defaults should be set/checked on core if `Enabled`

2024-06-03 08:57 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +            [];
this should be checked on core at publishing time

2024-06-03 08:58 UTC, lazedo requested changes
`defaults` and checked should be done at `publishing`

2024-06-12 13:17 UTC, lazedo commented on src/call_cmd/ecallmgr_call_command.erl
> +    FinalTimeout = kz_json:get_ne_binary_value([<<"Record-Silence-Detection">>, <<"Final-Timeout">>], JObj),
any reason for to getting as integers ? the `core` pr uses `integers`

2024-06-17 15:50 UTC, lazedo approved these changes

2024-06-17 15:52 UTC, merged