KZOO-531 Call recording status through API
2600hz/kazoo-ecallmgr pull request #264
Opened 2024-10-10 12:32 UTC by pavel-farkas

This PR is part of multiple PRs which enable to

- check recording status for a channel via API channel status call
- handle multiple recordings for a channel

This PR introduces `recording_status` field to `channel` record and adds functions to fetch and update its value.
Changes in `ecallmgr_fs_recordings` module allow for monitoring and handling all recording events and `update_state/2` function defines states transitions based on current recording state and received recording event.

Related JIRAs: 
https://oomacorp.atlassian.net/browse/KZOO-531

Group of related PRs:
https://github.com/2600hz/kazoo-core/pull/992
https://github.com/2600hz/kazoo-ecallmgr/pull/264
https://github.com/2600hz/kazoo-crossbar/pull/616
https://github.com/2600hz/kazoo-konami-pro/pull/56
https://github.com/2600hz/kazoo-ecallmgr-extension/pull/90

2024-10-10 14:15 UTC, lazedo requested changes
good initiative but needs to address some concerns

- a channel can have multiple recordings, what if the sequence is `start, start,stop, [in the middle], stop`, what is the result if channel is queried `[in the middle]`?

- what about `RECORD_PAUSE` and `RECORD_RESUME` handling ?

2024-10-10 14:19 UTC, lazedo commented
@pavel-farkas pull requests should be made against `master` branch and eventually backported if accepted

2024-10-10 14:22 UTC, pavel-farkas commented
thank you Luis for looking at it.

- yes you are right, we have already discussed these issues with @jamesaimonetti and decided to have common meeting with you and perhaps with Karl to address these. I will schedule one asap.

- This PR just strictly follows what customer asked for and it is just the beginning

2024-12-02 21:11 UTC, pavel-farkas commented on src/call_cmd/ecallmgr_call_command.erl
> +                        <<"all">> -> <<"all">>;
allows to use "all" instead of path to recording file, `stop_record_session` is the only dptool which accepts that

2024-12-03 14:00 UTC, pavel-farkas commented
The whole solution has been updated, taking into account comments from @lazedo. We can address individual recordings identifying them by their name  - or apply actions as batch command to all active recordings. Handlers for recording pause and resume were added.

2025-01-03 16:05 UTC, lazedo requested changes
drop the changes to `src/call_cmd/ecallmgr_call_command.erl`

need clarification on `src/ecallmgr_fs_channel.erl`

2025-01-03 16:05 UTC, lazedo commented on src/ecallmgr_fs_recordings.erl
> +                            ], ?MODULE, 'handle_recording_event'),
you can bind twice for record_stop. I would prefer to keep different handlers. leave `handle_record_stop` and add `RECORD_STOP` to new handler `handle_recording_event`

2025-01-03 16:05 UTC, lazedo commented on src/ecallmgr_fs_channel.erl
> +
failing to see the scope and reason for this

2025-01-03 16:05 UTC, lazedo commented on src/ecallmgr_fs_recordings.erl
> +                            ], ?MODULE, 'handle_recording_event'),
not sure why this was not handled in `ecallmgr_fs_channel_stream` as others

2025-01-03 16:05 UTC, lazedo commented on src/ecallmgr_fs_channel.erl
> +
where is this used from ?

2025-01-03 16:05 UTC, lazedo commented on src/ecallmgr_fs_channel.erl
> +        ,fetch_recording_names/1
where is this used from ?

2025-01-08 20:49 UTC, pavel-farkas commented on src/ecallmgr_fs_channel.erl
> +        ,fetch_recording_names/1
my bad, remnant from previous version, removed

2025-01-08 21:23 UTC, pavel-farkas commented on src/ecallmgr_fs_channel.erl
> +
remnant from previous version, removed.

2025-01-08 21:23 UTC, pavel-farkas commented on src/ecallmgr_fs_channel.erl
> +
remnant from previous version, removed.

2025-01-09 12:45 UTC, pavel-farkas commented on src/ecallmgr_fs_recordings.erl
> +                            ], ?MODULE, 'handle_recording_event'),
- done, `RECORD_STOP` has its specific handler back
- perhaps we should move `src/ecallmgr_fs_recordings.erl` to `src/event_stream` subfolder and rename it to `ecallmgr_fs_channel_stream_recording.erl` or something similar

2025-01-09 17:17 UTC, lazedo commented on src/ecallmgr_fs_recordings.erl
> -    kz_log:put_callid(UUID),
any reason for removing this ?

2025-01-10 13:56 UTC, pavel-farkas commented on src/ecallmgr_fs_recordings.erl
> -    kz_log:put_callid(UUID),
just because it is repeated in common handler for all events including `RECORD_STOP` - I've put it back

2025-01-10 14:44 UTC, lazedo approved these changes
update_recording_status should be revisited and probably removed and have the changes handled as other channels updates.

revisit when otp gives a callback for ets:update_element ensuring atomicity

2025-01-10 14:45 UTC, merged