CAG-31: Lookup endpoint registration based on authz_id and from_user
2600hz/kazoo-ecallmgr pull request #63
Opened 2020-12-18 00:13 UTC by jamesaimonetti

2020-12-18 01:11 UTC, jamesaimonetti commented
Needs https://github.com/2600hz/kazoo-core/pull/178 for xref check

2020-12-19 01:13 UTC, lazedo requested changes
lets talk

2020-12-22 08:11 UTC, lazedo commented on src/fetch/ecallmgr_fs_fetch_directory.erl
> +            {'ok', Xml} = ecallmgr_fs_xml:directory_resp_endpoint_xml(kz_json:set_value(<<"User-ID">>, EndpointId, Endpoint), JObj),
`kz_json:set_value(<<"User-ID">>, EndpointId, Endpoint)`  this should not be needed

2020-12-22 08:17 UTC, lazedo commented on src/fetch/ecallmgr_fs_fetch_directory.erl
>      case ecallmgr_registrar:lookup_endpoint(EndpointId, AccountId) of
any reason for changing order ? all others have `EndpointId, AccountId` order

2020-12-22 08:20 UTC, lazedo commented on src/ecallmgr_registrar.erl
> +    insert_registration(Registration#registration{authorizing_id=EndpointId
`authorizing_id=EndpointId` we should keep the original `authorizing_id`

2020-12-22 16:21 UTC, jamesaimonetti commented on src/fetch/ecallmgr_fs_fetch_directory.erl
> +            {'ok', Xml} = ecallmgr_fs_xml:directory_resp_endpoint_xml(kz_json:set_value(<<"User-ID">>, EndpointId, Endpoint), JObj),
@lazedo the endpoint is coming back with the device's ID as `User-ID` which causes FreeSWITCH to reject the auth.

2020-12-22 16:21 UTC, jamesaimonetti commented on src/fetch/ecallmgr_fs_fetch_directory.erl
> +            {'ok', Xml} = ecallmgr_fs_xml:directory_resp_endpoint_xml(kz_json:set_value(<<"User-ID">>, EndpointId, Endpoint), JObj),
auth is for token-id @ realm

2020-12-22 16:22 UTC, jamesaimonetti commented on src/fetch/ecallmgr_fs_fetch_directory.erl
>      case ecallmgr_registrar:lookup_endpoint(EndpointId, AccountId) of
Probably left over from reverting using the fetch_from_user stuff

2020-12-22 16:22 UTC, jamesaimonetti commented on src/ecallmgr_registrar.erl
> +    insert_registration(Registration#registration{authorizing_id=EndpointId
@lazedo so just replace id tuple with EndpointId ? I'll try it out!

2020-12-22 21:31 UTC, jamesaimonetti commented on src/ecallmgr_registrar.erl
> +    insert_registration(Registration#registration{authorizing_id=EndpointId
@lazedo since lookup_endpoint searches on `authorizing_id=EndpointId` and `EndpointId` is the device-id, two registrations are found. Would you support changing lookup_endpoint to use `id={EndpointId, _}` instead?

2020-12-24 00:27 UTC, merged