[add] external call sip headers to ets tables
2600hz/kazoo-ecallmgr pull request #85
Opened 2021-04-09 19:46 UTC by filipevarjao

This PR goals to address a customer request, we added User-to-User and P-Intrinsics info at ecallmgr ets tables for external calls. We're retrieving that info when freeswitch sends the dialplan request to ecallmgr

2021-04-12 18:49 UTC, lazedo requested changes
this looks very wrong

2021-04-12 18:49 UTC, lazedo commented on src/call_cmd/ecallmgr_fs_bridge.erl
> +                         ,<<"P-Intrinsics">>
what's this and why is it being added ?

2021-04-12 18:49 UTC, lazedo commented on src/ecallmgr.hrl
> +                 ,p_intrinsics :: kz_term:api_object() | '_'
why is this being added ?

2021-04-12 18:49 UTC, lazedo commented on src/ecallmgr_fs_channel.erl
> +      ,{<<"P-Intrinsics">>, Channel#channel.p_intrinsics}
why are these top level ?

2021-04-12 18:49 UTC, lazedo commented on src/ecallmgr_fs_channel.erl
> +
remove this empty line

2021-04-12 18:49 UTC, lazedo commented on src/ecallmgr_fs_channel.erl
> +    {CustomChannelVars} = proplists:get_value(<<"Custom-Channel-Vars">>, Payload),
what's this ? json object are not represented that way, check kz_json in stdlib, you may also look for other examples thru out the code base for proper handling of kz_json objects

2021-04-12 18:49 UTC, lazedo commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +
why is this being added ? route requests already have Custom-SIP-Headers included

2021-04-12 18:54 UTC, filipevarjao commented on src/ecallmgr_fs_channel.erl
> +    {CustomChannelVars} = proplists:get_value(<<"Custom-Channel-Vars">>, Payload),
my bad, later on I realized that is a JsonObj, and forget to update it, I can use the get_value for this case

2021-04-12 18:58 UTC, filipevarjao commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +
we might have Custom-SIP-Headers to inbound calls but not for an outbound call, one we only want to expose the  User-to-User and P-Intrinsics data we are retrieving when freeswitch sends the dialplan request to ecallmgr and we have to keep it somewhere, this is why I'm adding it

2021-04-12 19:00 UTC, lazedo commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +
outbound calls don't have route requests

2021-04-12 19:04 UTC, filipevarjao commented on src/ecallmgr.hrl
> +                 ,p_intrinsics :: kz_term:api_object() | '_'
a customer is sending that specific info on the header when doing an outbound call through kazoo, and they're requiring that info for qubicle events, maybe @mark2600 can provide more info about it

2021-04-12 19:11 UTC, filipevarjao commented on src/fetch/ecallmgr_fs_fetch_dialplan.erl
> +
then what would be your suggestion to get the User-to-User and P-Intrinsics?

2021-04-12 19:26 UTC, filipevarjao commented on src/call_cmd/ecallmgr_fs_bridge.erl
> +                         ,<<"P-Intrinsics">>
those keys are needed to bridge the call, otherwise, calls fail

2021-04-12 20:14 UTC, jamesaimonetti commented on src/ecallmgr_fs_channel.erl
> +    {CustomChannelVars} = proplists:get_value(<<"Custom-Channel-Vars">>, Payload),
@filipevarjao also please see `props` module for proplist-related stuff, it uses lists:key* functions (in C under the hood) vs proplists which uses pure Erlang

2021-04-12 20:40 UTC, filipevarjao commented on src/ecallmgr_fs_channel.erl
> +
ok

2021-04-12 20:43 UTC, filipevarjao commented on src/ecallmgr_fs_channel.erl
> +      ,{<<"P-Intrinsics">>, Channel#channel.p_intrinsics}
here is where pass the info when doing a channel query, so we need it

2021-04-13 12:32 UTC, lazedo commented
closed in favor of https://github.com/2600hz/kazoo-ecallmgr/pull/86

2021-04-13 12:32 UTC, closed without merging