PROD-169: split out failver from call forward
2600hz/kazoo-ecallmgr pull request #88
Opened 2021-04-23 22:04 UTC by icehess

Duplicate call forwarding settings into a failover object (account, user, device) and remove ‘failover’ as a call forward option.

The intend is to allow users to be able to change their call forwarding settings without impacting the failover settings and have failover set independently from forward.

2021-04-23 22:04 UTC, icehess commented
Required PR:
https://github.com/2600hz/kazoo-core/pull/257
https://github.com/2600hz/kazoo-crossbar/pull/179



**UPDATE**
New Required PR:
https://github.com/2600hz/kazoo-core/pull/263

2021-04-23 23:14 UTC, lazedo requested changes
element name should be `failover`

2021-04-23 23:14 UTC, lazedo commented on src/ecallmgr_fs_xml.erl
> +        Props -> variables_el('call-forward', [variable_el(K, callfwd_property(K, V)) || {K, V} <- Props])
```suggestion
        Props -> variables_el('failover', [variable_el(K, callfwd_property(K, V)) || {K, V} <- Props])
```

2021-07-05 13:50 UTC, lazedo approved these changes

2021-07-05 13:51 UTC, merged